export type RootStackParamList = {
  Welcome: undefined;
  Login: undefined;
  Register: undefined;
  Forgot: undefined;
  Home: undefined;
  Subir: undefined;
  Procesando: undefined;
  Resultado: { analysisId: string };
  Comparacion: { analysisId: string };
  Morfologia: undefined;
  MorfologiaResultado: { scanId: string };
  Chat: { initialQuestion?: string } | undefined;
  Progreso: undefined;
  Concursos: undefined;
  Veredicto: { veredictoId: string };
  Perfil: undefined;
  EditarPerfil: undefined;
  NuevoCaballo: { editId?: string } | undefined;
  AjustesMenu: undefined;
  AjustesNivel: undefined;
  AjustesNotif: undefined;
  AjustesSuscripcion: undefined;
};
